[build]
  command = "chmod +x netlify.sh && bash netlify.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2" }

[context.deploy-preview]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[template.environment]
  CECIL_SITE_TITLE = "Blog's title"
  CECIL_SITE_BASELINE = "Short description (~ 20 characters)"
  CECIL_SITE_DESCRIPTION = "Full description (~ 250 characters)"
